# Generated by Django 4.1.4 on 2022-12-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20, verbose_name='آیدی')),
                ('ename', models.CharField(max_length=100, verbose_name='نام')),
                ('elname', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('eemail', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('econtact', models.CharField(max_length=11, verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'db_table': 'employee',
            },
        ),
    ]
